version: '3.5'
services:
  rstudio: 
    container_name: rstudio
    image: aabor/rstudio:latest
    build: rstudio/.
    volumes:
      - ~docker/rstudio/rstudio:/home/rstudio
      - ~/R:/home/rstudio/R
      - ~/Documents:/home/rstudio/Documents
      - ~/.ssh:/home/rstudio/.ssh/  
      - ~/.secrets:/home/rstudio/.secrets/  
      - ~/.httr-oauth:/home/rstudio/.httr-oauth
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - ~docker/rstudio/rstudio:/srv/shiny-server 
      - ~docker/rstudio/rstudio/.log:/var/log/shiny-server
    ports:
      - "8787:8787"
      - "3838:3838"
    environment:
      - TZ="Europe/Kiev"
      - GIT_VERSION=$GIT_VERSION
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: always
    networks: 
      - selenium-hub
  rstudio-finance: 
    container_name: rstudio-finance
    image: aabor/rstudio-finance:latest
    build: rstudio-finance/.
    volumes:
      - ~docker/rstudio/rstudio-finance:/home/rstudio  
      - ~/R:/home/rstudio/R
      - ~/Documents:/home/rstudio/Documents
      - ~/Documents/Trading/fh_data-dev:$FH_PATH/data
      - ~/Documents/Trading/csv-arch:$FH_PATH/data/csv-arch
      - ~/Documents/Trading/news-arch:$FH_PATH/data/news-arch
      - $MT4_PATH/data-dev:$FH_PATH/data/mt4
      - ~/.ssh:/home/rstudio/.ssh/  
      - ~/.secrets:/home/rstudio/.secrets/  
      - ~/.httr-oauth:/home/rstudio/.httr-oauth
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - ~docker/rstudio/rstudio-finance:/srv/shiny-server 
      - ~docker/rstudio/rstudio-finance/.log:/var/log/shiny-server
    ports:
      - "8788:8787"
      - "3839:3838"
    environment:
      - TZ="Europe/Kiev"
      - GIT_VERSION=$GIT_VERSION
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: always
    networks: 
      - selenium-hub
  rstudio-text: 
    container_name: rstudio-text
    image: aabor/rstudio-text:latest
    build: rstudio-text/.
    volumes:
      - ~docker/rstudio/rstudio-text:/home/rstudio  
      - ~/R:/home/rstudio/R
      - ~/Documents:/home/rstudio/Documents
      - ~/.ssh:/home/rstudio/.ssh/  
      - ~/.secrets:/home/rstudio/.secrets/  
      - ~/.httr-oauth:/home/rstudio/.httr-oauth
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - ~docker/rstudio/rstudio-text:/srv/shiny-server 
      - ~docker/rstudio/rstudio-text/.log:/var/log/shiny-server      
    ports:
      - "8789:8787"
      - "3840:3838"
    environment:
      - TZ="Europe/Kiev"
      - GIT_VERSION=$GIT_VERSION
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: always
    networks: 
      - selenium-hub
networks:
  selenium-hub:
    external: true
