version: '2'
services:
  selenium:
    image: selenium/standalone-firefox:3.141.59-bismuth
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
      - /home/$USER/r-projects/downloads:/home/seluser/Downloads
    container_name: selenium
    networks: 
      - backend
    restart: always
  rstudio: 
    image: aabor/rstudio
    build: .
    volumes:
      # executable scripts
      - /home/$USER/r-projects/rstudio:/home/rstudio
      # SSH keys
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      # shiny server
      - /home/$USER/r-projects/rstudio:/srv/shiny-server 
      - /home/$USER/r-projects/rstudio/.log:/var/log/shiny-server
    ports:
      - "8787:8787"
      - "3838:3838"
    environment:
      - USER=rstudio
      - PASSWORD=123
    container_name: rstudio
    networks: 
      - backend
    restart: always
    depends_on:
      - selenium
networks: 
  backend:
    driver: bridge