version: '3.5'
services:
  selenium-hub:
    image: selenium/hub:3.141.59-xenon
    environment:
      - GRID_MAX_SESSION=15
      - GRID_TIMEOUT=180000
      - GRID_BROWSER_TIMEOUT=180000      
    networks: 
      - selenium-hub
  chrome:
    image: selenium/node-chrome:3.141.59-xenon
    shm_size: 512MB
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=6
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /home/$USER/Downloads/Selenium:/home/seluser/Downloads
    networks: 
      - selenium-hub      
    restart: always
  rstudio: 
    image: aabor/rstudio
    build: rstudio/.
    volumes:
      - /home/$USER/projects/rstudio/rstudio:/home/rstudio
      - /home/$USER/projects:/home/rstudio/R
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      - /home/$USER/.httr-oauth:/home/rstudio/.httr-oauth
      - /home/$USER/.gitconfig:/home/rstudio/.gitconfig
      - /home/$USER/.Renviron:/home/rstudio/.Renviron
      - /home/$USER/projects/rstudio/rstudio:/srv/shiny-server 
      - /home/$USER/projects/rstudio/rstudio/.log:/var/log/shiny-server
    ports:
      - "8787:8787"
      - "3838:3838"
    environment:
      - TZ="EEST"
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: "on-failure:30"
    depends_on:
      - chrome
    networks: 
      - selenium-hub
      - front-end 
  rstudio-finance: 
    image: aabor/rstudio-finance
    build: rstudio-finance/.
    volumes:
      - /home/$USER/projects/rstudio/rstudio-finance:/home/rstudio  
      - /home/$USER/projects:/home/rstudio/R
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/Documents/Trading/fh:/home/rstudio/R/fh/data
      - /home/$USER/Documents/Trading/quotes-csv-arch:/home/rstudio/R/fh/data/quotes-csv-arch
      - /home/$USER/Documents/Trading/news-csv-arch:/home/rstudio/R/fh/data/news-csv-arch
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      - /home/$USER/.httr-oauth:/home/rstudio/.httr-oauth
      - /home/$USER/.gitconfig:/home/rstudio/.gitconfig
      - /home/$USER/.Renviron:/home/rstudio/.Renviron
      - /home/$USER/projects/rstudio/rstudio-finance:/srv/shiny-server 
      - /home/$USER/projects/rstudio/rstudio-finance/.log:/var/log/shiny-server
    ports:
      - "8788:8787"
      - "3839:3838"
    environment:
      - TZ="EEST"
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: always
    depends_on:
      - chrome
    networks: 
      - selenium-hub
      - front-end
  rstudio-text: 
    image: aabor/rstudio-text
    build: rstudio-text/.
    volumes:
      - /home/$USER/projects/rstudio/rstudio-text:/home/rstudio  
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/projects:/home/rstudio/R
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      - /home/$USER/.httr-oauth:/home/rstudio/.httr-oauth
      - /home/$USER/.gitconfig:/home/rstudio/.gitconfig
      - /home/$USER/.Renviron:/home/rstudio/.Renviron
      - /home/$USER/projects/rstudio/rstudio-text:/srv/shiny-server 
      - /home/$USER/projects/rstudio/rstudio-text/.log:/var/log/shiny-server      
    ports:
      - "8789:8787"
      - "3840:3838"
    environment:
      - TZ="EEST"
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: always
    networks: 
      - selenium-hub
      - front-end
    depends_on:
      - chrome
  nbdatascience: 
    image: aabor/nbdatascience
    build: nbdatascience/.
    volumes:
      - /home/$USER/Documents:/home/jovyan/Documents
      - /home/$USER/Documents/Trading/fh:/home/jovyan/work/R/fh/data
      - /home/$USER/Documents/Trading/news-csv-arch:/home/jovyan/work/R/fh/data/news-csv-arch
      - /home/$USER/projects:/home/jovyan/work
      - /home/$USER/.jupyter:/home/jovyan/.jupyter
      #- /home/$USER/.kaggle:/home/jovyan/.kaggle
      - /home/$USER/.ssh:/home/jovyan/.ssh/  
      - /home/$USER/.secrets:/home/jovyan/.secrets/  
      - /home/$USER/.httr-oauth:/home/jovyan/.httr-oauth
      - /home/$USER/.gitconfig:/home/jovyan/.gitconfig
    ports:
      - 10000:8888
    environment:
      - TZ="EEST"
      - WERKZEUG_DEBUG_PIN=off
    restart: always
    depends_on:
      - chrome
    networks: 
      - selenium-hub
      - front-end      
networks:
  selenium-hub:
    external: true
  front-end:
    external: true
volumes:
  my-db:
