version: '2'
services:
  dropbox:
    image: janeczku/dropbox
    # ports:
    #   - "17500:17500"
    volumes:
      - /home/$USER/r-projects/rstudio/Dropbox-docker:/dbox/Dropbox
      - /home/$USER/r-projects/rstudio/.dropbox:/dbox/.dropbox-docker
    environment:
      - DBOX_UID=$DBOX_UID
      - DBOX_GID=$DBOX_GID
    restart: always
    networks: 
      - backend
    container_name: dropbox
  selenium:
    image: selenium/standalone-firefox:3.141.59-bismuth
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
      - /home/$USER/r-projects/rstudio/downloads:/home/seluser/Downloads
    container_name: selenium
    networks: 
      - backend
    restart: always
  rstudio: 
    image: aabor/rstudio
    build: .
    volumes:
      # executable scripts
      - /home/$USER/r-projects/rstudio:/home/rstudio
      - /home/$USER/Documents/textbooks:/home/rstudio/textbooks
      # folder with quotes updated by MetaTrader
      - /home/$USER/Dropbox/mt4quotes/Data:/home/rstudio/mt4quotes
      # SSH keys
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      # shiny server
      - /home/$USER/r-projects/rstudio:/srv/shiny-server 
      - /home/$USER/r-projects/rstudio/.log:/var/log/shiny-server
    ports:
      - "8787:8787"
      - "3838:3838"
    environment:
      - USER=rstudio
      - PASSWORD=123
    container_name: rstudio
    networks: 
      - backend
    restart: always
    depends_on:
      - selenium
  rstudio-finance: 
    image: aabor/rstudio-finance
    build: ../../rstudio-finance/docker-image/
    volumes:
      # executable scripts
      - /home/$USER/r-projects/rstudio-finance:/home/rstudio  
      - /home/$USER/Documents/textbooks:/home/rstudio/textbooks
      # SSH keys
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      # folder with quotes updated by MetaTrader
      - /home/$USER/Dropbox/mt4quotes/Data:/home/rstudio/mt4quotes
      # shiny server
      - /home/$USER/r-projects/rstudio-finance:/srv/shiny-server 
      - /home/$USER/r-projects/rstudio-finance/.log:/var/log/shiny-server
    ports:
      - "8788:8787"
      - "3839:3838"
    environment:
      - USER=rstudio
      - PASSWORD=123
    links:
      - selenium:selenium
    container_name: rstudio-finance
    networks: 
      - backend
    restart: always
  rstudio-text: 
    image: aabor/rstudio-text
    build: ../../rstudio-text/docker-image/
    volumes:
      # executable scripts
      - /home/$USER/r-projects/rstudio-text:/home/rstudio  
      - /home/$USER/Documents/textbooks:/home/rstudio/textbooks
      # folder with quotes updated by MetaTrader
      - /home/$USER/Dropbox/mt4quotes/Data:/home/rstudio/mt4quotes
      # SSH keys
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      # shiny server
      - /home/$USER/r-projects/rstudio-text:/srv/shiny-server 
      - /home/$USER/r-projects/rstudio-text/.log:/var/log/shiny-server      
    ports:
      - "8789:8787"
      - "3840:3838"
    environment:
      - USER=rstudio
      - PASSWORD=123
    depends_on:
      - selenium
    container_name: rstudio-text
    networks: 
      - backend
    restart: always
networks: 
  backend:
    driver: bridge