version: '3.5'
services:
  rstudio: 
    image: aabor/rstudio
    build: rstudio/.
    volumes:
      - /home/$USER/rstudio/rstudio:/home/rstudio
      - /home/$USER/projects:/home/rstudio/R
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      - /home/$USER/.httr-oauth:/home/rstudio/.httr-oauth
      - /home/$USER/.gitconfig:/home/rstudio/.gitconfig
      - /home/$USER/.Renviron:/home/rstudio/.Renviron
      - /home/$USER/rstudio/rstudio:/srv/shiny-server 
      - /home/$USER/rstudio/rstudio/.log:/var/log/shiny-server
    ports:
      - "8787:8787"
      - "3838:3838"
    environment:
      - TZ="EEST"
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: "on-failure:30"
    networks: 
      - selenium-hub
      - front-en
      - host
  rstudio-finance: 
    image: aabor/rstudio-finance
    build: rstudio-finance/.
    volumes:
      - /home/$USER/rstudio/rstudio-finance:/home/rstudio  
      - /home/$USER/projects:/home/rstudio/R
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/Documents/Trading/fh:/home/rstudio/R/fh/data
      - /home/$USER/Documents/Trading/quotes-csv-arch:/home/rstudio/R/fh/data/quotes-csv-arch
      - /home/$USER/Documents/Trading/news-csv-arch:/home/rstudio/R/fh/data/news-csv-arch
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      - /home/$USER/.httr-oauth:/home/rstudio/.httr-oauth
      - /home/$USER/.gitconfig:/home/rstudio/.gitconfig
      - /home/$USER/.Renviron:/home/rstudio/.Renviron
      - /home/$USER/rstudio/rstudio-finance:/srv/shiny-server 
      - /home/$USER/rstudio/rstudio-finance/.log:/var/log/shiny-server
    ports:
      - "8788:8787"
      - "3839:3838"
    environment:
      - TZ="EEST"
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: always
    networks: 
      - selenium-hub
      - front-end
      - host
  rstudio-text: 
    image: aabor/rstudio-text
    build: rstudio-text/.
    volumes:
      - /home/$USER/rstudio/rstudio-text:/home/rstudio  
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/projects:/home/rstudio/R
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      - /home/$USER/.httr-oauth:/home/rstudio/.httr-oauth
      - /home/$USER/.gitconfig:/home/rstudio/.gitconfig
      - /home/$USER/.Renviron:/home/rstudio/.Renviron
      - /home/$USER/rstudio/rstudio-text:/srv/shiny-server 
      - /home/$USER/rstudio/rstudio-text/.log:/var/log/shiny-server      
    ports:
      - "8789:8787"
      - "3840:3838"
    environment:
      - TZ="EEST"
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: always
    networks: 
      - selenium-hub
      - front-end
      - host
networks:
  selenium-hub:
    external: true
  front-end:
    external: true
