version: '3'
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-firefox:3.141.59-bismuth
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
      - /home/$USER/Selenium:/home/seluser/Downloads
    networks: 
      - backend
    restart: always
  rstudio: 
    container_name: rstudio
    image: aabor/rstudio:latest
    build: /home/$USER/docker/rstudio
    volumes:
      - /home/$USER/r-projects/rstudio:/home/rstudio
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/Selenium:/home/rstudio/Selenium
      # SSH keys
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      # Secrets
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      # shiny server
      - /home/$USER/r-projects/rstudio:/srv/shiny-server 
      - /home/$USER/r-projects/rstudio/.log:/var/log/shiny-server
    ports:
      - "8787:8787"
      - "3838:3838"
    environment:
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    networks: 
      - backend
    restart: always
    depends_on:
      - selenium
  rstudio-finance: 
    container_name: rstudio-finance
    image: aabor/rstudio-finance:latest
    build: /home/$USER/docker/rstudio-finance
    volumes:
      - /home/$USER/r-projects/rstudio-finance:/home/rstudio  
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/Selenium:/home/rstudio/Selenium
      - /home/$USER/Documents/Trading/fh_data-dev:/home/rstudio/projects/fh/data
      # folder with quotes updated by MetaTrader
      - /home/$USER/Dropbox/mt4/data-dev:/home/rstudio/projects/fh/data/mt4
      # SSH keys
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      # Secrets
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      - /home/$USER/.httr-oauth:/home/rstudio/projects/fh/.httr-oauth
      # shiny server
      - /home/$USER/r-projects/rstudio-finance:/srv/shiny-server 
      - /home/$USER/r-projects/rstudio-finance/.log:/var/log/shiny-server
    ports:
      - "8788:8787"
      - "3839:3838"
    environment:
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    links:
      - selenium:selenium
    networks: 
      - backend
    restart: always
    depends_on:
      - selenium
  rstudio-text: 
    container_name: rstudio-text
    image: aabor/rstudio-text:latest
    build: /home/$USER/docker/rstudio-text
    volumes:
      - /home/$USER/r-projects/rstudio-text:/home/rstudio  
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/Selenium:/home/rstudio/Selenium
      # SSH keys
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      # Secrets
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      # shiny server
      - /home/$USER/r-projects/rstudio-text:/srv/shiny-server 
      - /home/$USER/r-projects/rstudio-text/.log:/var/log/shiny-server      
    ports:
      - "8789:8787"
      - "3840:3838"
    environment:
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    networks: 
      - backend
    restart: always
    depends_on:
      - selenium
networks: 
  backend:
    driver: bridge
