version: '3.5'
services:
  rstudio: 
    image: aabor/rstudio
    build: rstudio/.
    volumes:
      - /home/$USER/rstudio/rstudio:/home/rstudio
      - /home/$USER/R:/home/rstudio/R
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      - /home/$USER/.httr-oauth:/home/rstudio/.httr-oauth
      - /home/$USER/.gitconfig:/home/rstudio/.gitconfig
      - /home/$USER/rstudio/rstudio:/srv/shiny-server 
      - /home/$USER/rstudio/rstudio/.log:/var/log/shiny-server
    ports:
      - "8787:8787"
      - "3838:3838"
    environment:
      - TZ="Europe/Kiev"
      - GIT_VERSION=$GIT_VERSION
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: "on-failure:30"
    networks: 
      - selenium-hub
      - front-end
  rstudio-finance: 
    image: aabor/rstudio-finance
    build: rstudio-finance/.
    volumes:
      - /home/$USER/rstudio/rstudio-finance:/home/rstudio  
      - /home/$USER/R:/home/rstudio/R
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/Documents/Trading/fh_data-dev:$FH_PATH/data
      - /home/$USER/Documents/Trading/csv-arch:$FH_PATH/data/csv-arch
      - /home/$USER/Documents/Trading/news-arch:$FH_PATH/data/news-arch
      - $MT4_PATH/data-dev:$FH_PATH/data/mt4
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      - /home/$USER/.httr-oauth:/home/rstudio/.httr-oauth
      - /home/$USER/.gitconfig:/home/rstudio/.gitconfig
      - /home/$USER/rstudio/rstudio-finance:/srv/shiny-server 
      - /home/$USER/rstudio/rstudio-finance/.log:/var/log/shiny-server
    ports:
      - "8788:8787"
      - "3839:3838"
    environment:
      - TZ="Europe/Kiev"
      - GIT_VERSION=$GIT_VERSION
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: "on-failure:30"
    networks: 
      - selenium-hub
      - front-end
  rstudio-text: 
    image: aabor/rstudio-text
    build: rstudio-text/.
    volumes:
      - /home/$USER/rstudio/rstudio-text:/home/rstudio  
      - /home/$USER/R:/home/rstudio/R
      - /home/$USER/Documents:/home/rstudio/Documents
      - /home/$USER/.ssh:/home/rstudio/.ssh/  
      - /home/$USER/.secrets:/home/rstudio/.secrets/  
      - /home/$USER/.httr-oauth:/home/rstudio/.httr-oauth
      - /home/$USER/.gitconfig:/home/rstudio/.gitconfig
      - /home/$USER/rstudio/rstudio-text:/srv/shiny-server 
      - /home/$USER/rstudio/rstudio-text/.log:/var/log/shiny-server      
    ports:
      - "8789:8787"
      - "3840:3838"
    environment:
      - TZ="Europe/Kiev"
      - GIT_VERSION=$GIT_VERSION
      - USER=rstudio
      - PASSWORD=$RSTUDIO_COMMON_CREDS_PSW
    restart: "on-failure:30"
    networks: 
      - selenium-hub
      - front-end
networks:
  selenium-hub:
    external: true
  front-end:
    external: true
