version: '3'
services:
  sut:
    build: .
    command: 
    - /bin/sh 
    - -c 
    - |
      uname -a 
      R --version
      Rscript -e "Sys.info()"
      Rscript -e "sessionInfo()"
    
    # depends_on:
    #   - selenium
    #   - rstudio-finance
    # networks:
    #   - backend
