pipeline {
    agent any
    stages {
        stage('Build') {
            environment { 
                USER=credentials('jenkins-current-user')
                DOCKER_CREDS=credentials('jenkins-docker-credentials')
                RSTUDIO_COMMON_CREDS = credentials('jenkins-rstudio-common-creds')
                RSTUDIO_PATH="/home/$USER/rstudio"
                DOCUMENTS_PATH="/home/$USER/Documents"
                SELENIUM_PATH="/home/$USER/Selenium"
                MT4_PATH="/home/$USER/Dropbox/mt4"
            }            
            steps {
                echo 'Building..'
                sh 'docker-compose -f /home/$USER/docker/rstudio/docker-compose.yml build'
                echo 'login to docker'
                sh 'docker login -u $DOCKER_CREDS_USR  -p $DOCKER_CREDS_PSW'
                echo 'Pushing rstudio:latest to docker hub'
                sh 'docker push aabor/rstudio:latest'
                echo 'Pushing rstudio-finance:latest to docker hub'
                sh 'docker push aabor/rstudio-finance:latest'
                echo 'Pushing rstudio-text:latest to docker hub'
                sh 'docker push aabor/rstudio-text:latest'
                echo 'starting docker containers'
                sh 'docker-compose -f /home/$USER/docker/rstudio/docker-compose.yml up -d --remove-orphans'
                mail    body: 'containers selenium, rstudio, rstudio-finance, rstudio-text started',
                        from: 'aaborochkin@gmail.com',
                        subject: 'rocker successfully rolled out',
                        to: 'aaborochkin@gmail.com'  
            }
        }
    }
}
