pipeline {
    agent any
    stages {
        stage('Build') {
            environment { 
                USER=credentials('jenkins-current-user')
                DOCKER_CREDS=credentials('jenkins-docker-credentials')
                RSTUDIO_COMMON_CREDS = credentials('jenkins-rstudio-common-creds')
                MT4_PATH="/home/$USER/Dropbox/mt4"
                FH_PATH="/home/rstudio/R/fh"
            }            
            steps {
                echo 'Building..'
                sh '''
                    sh/build_image.sh                    
                    echo 'login to docker'
                    docker login -u $DOCKER_CREDS_USR  -p $DOCKER_CREDS_PSW
                    export GIT_VERSION=$(git describe --tags | sed s/v//)
                    echo $GIT_VERSION
                    echo "Pushing rstudio:$GIT_VERSION to docker hub"
                    docker push aabor/rstudio:$GIT_VERSION
                    docker push aabor/rstudio:latest
                    echo "Pushing rstudio-finance:$GIT_VERSION to docker hub"
                    docker push aabor/rstudio-finance:$GIT_VERSION
                    docker push aabor/rstudio-finance:latest
                    echo "Pushing rstudio-text:$GIT_VERSION to docker hub"
                    docker push aabor/rstudio-text:$GIT_VERSION
                    docker push aabor/rstudio-text:latest
                    echo "starting docker containers"
                    docker-compose up -d --remove-orphans
                '''
                mail    body: 'containers rstudio, rstudio-finance, rstudio-text started',
                        from: 'aaborochkin@gmail.com',
                        subject: 'rocker successfully rolled out',
                        to: 'aaborochkin@gmail.com'  
            }
            post {
                always{
                    cleanWs()
                    sh '''
                        pwd
                        ls
                        echo "Finishing.."
                    '''
                }
            }
        }
    }
}
